version: "3.7"
services:
  
  workspace:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: workspce
    ports:
      - 80:3000
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html/
      - ${WSL_ROOT_LARA}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${WSL_ROOT_LARA}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  # コンテナ名がPDO接続先のHOSTになる
  mysql: 
    image: mysql:5.7
    container_name: mysql
    init: true
    depends_on:
      - php-fpm
    ports:
      - 3306:3306
    volumes: 
      # - ${MYSQL_PATH_INIT}:/docker-entrypoint-initdb.d
      # - ${MYSQL_PATH_MYCONF}:/etc/mysql/my.cnf
      - ${MYSQL_PATH_DATA}:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=my_app
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  myadmin: 
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    init: true
    environment: 
      - PMA_HOST=mysql
#      - VIRTUAL_HOST=admin.gestem.keham
    ports: 
      - '9096:80'

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
